### ISSUE TITLE
Invalid dependencies Error and Can't run (Unity 2020.2.0b1)

### ISSUE THREAD

**Issue by myozinaung** [zalo/MathUtilities#2]
I got the error shown in the attached image when the project was opened in Unity 2020.2.0b1.
Any solution to that?
![Annotation 2020-09-03 205929](https://user-images.githubusercontent.com/26024258/92112476-cafe7e00-ee28-11ea-9a98-5491d96fddc0.png)

**Comment by sionfletcher** [comment]
Try changing line 43 in /Packages/manifest.json

~~`"registry": "https://staging-packages.unity.com"`~~
`"registry": "https://packages.unity.com"`
