### ISSUE TITLE
[Question] NelderMead or NumericalGradientDescent for multiple points

### ISSUE THREAD

**Issue by FreakTheMighty** [zalo/MathUtilities#4]
I'm looking at the examples for these optimizers and they appear to only optimize a single vertex. The problem I would like to solve is given a set of distance between many points, find a location for each point that maintains the correct distance for all points. The cost function would be the sum of the squared difference between the expected distance and the actual distance.

Do you think the solvers in your library could help with this problem?

**Comment by zalo** [comment]
Apologies for the late response… on one hand, yes, you should be able to define whatever cost function you like.

On the other hand, these implementations are not optimized for speed or robustness, and should primarily be considered educational reference for learning.

Lastly, it sounds like you’re doing a big distance constraint solver, which is one area where a bespoke constraint solving system (with gauss-seidel steps, graph coloring, substepping, etc.) will help far more than a general optimizer.

The “Verlet” folder may have elements that are more useful for this case. 

Have you seen my blog post which is an intro to distance constraint solvers?
https://zalo.github.io/blog/constraints/
